import Head from 'next/head';
import AppointmentForm from '../components/Appoinment';
import Views from '../components/Views';

export default function Home() {
  return (
    <>
      <Head>
        <title>Appointment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex flex-col lg:flex-row gap-4 w-full">
          <div className="border w-full dark:border-gray-600 p-4 dark:bg-gray-700 dark:text-gray-200">
            <AppointmentForm />
          </div>
          <div className="border dark:border-gray-600 w-full p-4 dark:bg-gray-700 dark:text-gray-200">
            <Views />
          </div>
        </div>
      </main>
    </>
  )
}
